arquivo = open("palavras.txt", "a")
arquivo.write("Goiaba\n")
arquivo.write("Laranja\n")
arquivo.write("Limão\n")
arquivo.write("Mamão\n")
arquivo.write("Manga\n")
arquivo.write("Maracujá\n")
arquivo.write("Melão\n")
arquivo.close()